### ISSUE TITLE
"EventEmitter memory leak detected" warning from Node.js

### ISSUE THREAD

**Issue by michaelmyers** [bespoken/bst#195]
It seems innocuous however sometimes when running the proxy, I get the following red warning from node:

```
INFO  2017-01-25T16:43:36.370Z Forwarding localhost:10000
(node) warning: possible EventEmitter memory leak detected. %d %s listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.addListener (events.js:239:17)
    at LoglessContext.onLambdaEvent (/Users/michaelmyers/Development/MyB100/node_modules/bespoken-tools/lib/logless/logless-context
.js:42:17)
    at LambdaWrapper.handle (/Users/michaelmyers/Development/MyB100/node_modules/bespoken-tools/lib/logless/logless.js:21:16)
    at LambdaServer.invoke (/Users/michaelmyers/.nvm/versions/node/v4.3.2/lib/node_modules/bespoken-tools/lib/client/lambda-server.
js:98:25)
    at IncomingMessage.<anonymous> (/Users/michaelmyers/.nvm/versions/node/v4.3.2/lib/node_modules/bespoken-tools/lib/client/lambda
-server.js:54:26)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickDomainCallback (node.js:392:17)
```

**Comment by jperata** [comment]
Might have been solved in one of the dependencies updates, haven't seen that issue, and haven't have another report from it. CLosing from now, we might reopen
