### ISSUE TITLE
Error loading .env file on start of tests

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#259]
We get errors when the unit tests run on Travis and they first start. They don't affect the tests, but they do pollute the logs:
```
{ Error: ENOENT: no such file or directory, open '.env'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.config (/home/travis/build/bespoken/bst/node_modules/dotenv/lib/main.js:30:37)
    at Object.<anonymous> (/home/travis/build/bespoken/bst/test/bin/bst-deploy-test.js:19:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/home/travis/build/bespoken/bst/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /home/travis/build/bespoken/bst/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/travis/build/bespoken/bst/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/home/travis/build/bespoken/bst/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/home/travis/build/bespoken/bst/node_modules/mocha/bin/_mocha:404:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/home/travis/build/bespoken/bst/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
    at runFn (/home/travis/build/bespoken/bst/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
    at /home/travis/build/bespoken/bst/node_modules/istanbul/lib/command/common/run-with-cover.js:251:17
    at /home/travis/build/bespoken/bst/node_modules/istanbul/lib/util/file-matcher.js:68:16
    at /home/travis/build/bespoken/bst/node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at /home/travis/build/bespoken/bst/node_modules/istanbul/node_modules/async/lib/async.js:361:13
    at /home/travis/build/bespoken/bst/node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at done (/home/travis/build/bespoken/bst/node_modules/istanbul/node_modules/async/lib/async.js:246:17)
    at /home/travis/build/bespoken/bst/node_modules/istanbul/node_modules/async/lib/async.js:44:16
    at /home/travis/build/bespoken/bst/node_modules/istanbul/node_modules/async/lib/async.js:358:17
    at LOOP (fs.js:1716:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
{ Error: ENOENT: no such file or directory, open '.env'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.config (/home/travis/build/bespoken/bst/node_modules/dotenv/lib/main.js:30:37)
    at Object.<anonymous> (/home/travis/build/bespoken/bst/test/client/bst-deploy-test.js:45:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/home/travis/build/bespoken/bst/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /home/travis/build/bespoken/bst/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/travis/build/bespoken/bst/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/home/travis/build/bespoken/bst/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/home/travis/build/bespoken/bst/node_modules/mocha/bin/_mocha:404:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/home/travis/build/bespoken/bst/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
    at runFn (/home/travis/build/bespoken/bst/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
    at /home/travis/build/bespoken/bst/node_modules/istanbul/lib/command/common/run-with-cover.js:251:17
    at /home/travis/build/bespoken/bst/node_modules/istanbul/lib/util/file-matcher.js:68:16
    at /home/travis/build/bespoken/bst/node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at /home/travis/build/bespoken/bst/node_modules/istanbul/node_modules/async/lib/async.js:361:13
    at /home/travis/build/bespoken/bst/node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at done (/home/travis/build/bespoken/bst/node_modules/istanbul/node_modules/async/lib/async.js:246:17)
    at /home/travis/build/bespoken/bst/node_modules/istanbul/node_modules/async/lib/async.js:44:16
    at /home/travis/build/bespoken/bst/node_modules/istanbul/node_modules/async/lib/async.js:358:17
    at LOOP (fs.js:1716:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
```

**Comment by jperata** [comment]
No longer showing as the most recent build in circle.
