### ISSUE TITLE
Socket race conditions

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#57]
Opening this issue to capture where this occurs so we know where to tighten code:
BSTProxy #http() Starts and Stops Correctly With Options:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

Add any other observed cases as comments.

UPDATE - this first one should be taken care of.

**Comment by jkelvie** [comment]
Another one:
 BespokeClient KeepAlive worked Gets lots of keep alives:
Cannot write data to null

**Comment by jkelvie** [comment]
1) BespokeServerTest ReceiveWebhook Connects and Receives Callback:
     Uncaught SyntaxError: Unexpected token N in JSON at position 0
      at Object.parse (native)
      at test/server/bespoke-server-test.js:27:33
      at IncomingMessage.<anonymous> (lib/core/http-client.js:9:1449)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by jkelvie** [comment]
LambdaRunner #start() Handles Reload Correctly:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test

**Comment by jkelvie** [comment]
This looks like a fun one:
Uncaught Error: watch /home/travis/build/bespoken/bst ENOSPC
      at exports._errnoException (util.js:870:11)
      at FSWatcher.start (fs.js:1234:19)
      at Object.fs.watch (fs.js:1262:11)
      at LambdaRunner.start (lib/client/lambda-runner.js:9:1421)
      at BSTProxy.start (lib/client/bst-proxy.js:9:3408)
      at test/client/bst-proxy-test.js:50:23
      at callbackCounter (lib/server/bespoke-server.js:9:1214)
      at Server.<anonymous> (lib/server/webhook-manager.js:9:3159)
      at emitListeningNT (net.js:1260:10)

**Comment by jkelvie** [comment]
1) LambdaRunner #start() Handles Reload Correctly:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

**Comment by jkelvie** [comment]
1) SkillInvoker #say Handles default on bad Phrase:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.

**Comment by jkelvie** [comment]
1) BSTProxy #http() Starts and Stops Correctly With Options:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
  
  2) BSTProxy #lambda() Starts and Stops Correctly:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

**Comment by jkelvie** [comment]
1) BSTProxy #http() Starts and Stops Correctly With Options:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

**Comment by jkelvie** [comment]
One more:
1) BSTAlexa Speaks and Intends "before each" hook for "Speak non-grammar phrase":
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

Going to probably start tracking these an individual issues after this one - have had better luck lately.

**Comment by jkelvie** [comment]
Declaring victory for now....much better performance at this point.

More issues to be opened as we see errors going forward.
