### ISSUE TITLE
Add better error message if multiple versions of proxy running

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#75]
This is what shows up now:

Error: listen EADDRINUSE :::10000
   at Object.exports._errnoException (util.js:1007:11)
   at exports._exceptionWithHostPort (util.js:1030:20)
   at Server._listen2 (net.js:1253:14)
   at listen (net.js:1289:10)
   at Server.listen (net.js:1385:5)
   at LambdaRunner.start (/usr/local/lib/node_modules/bespoken-tools/lib/client/lambda-runner.js:45:21)
   at BSTProxy.start (/usr/local/lib/node_modules/bespoken-tools/lib/client/bst-proxy.js:52:31)
   at Command.<anonymous> (/usr/local/lib/node_modules/bespoken-tools/bin/bst-proxy.js:45:11)
   at Command.listener (/usr/local/lib/node_modules/bespoken-tools/node_modules/commander/index.js:301:8)
   at emitTwo (events.js:106:13)

**Comment by simocl** [comment]
Hi,

Great tool!

Will it be possible to specify a different localhost port when running bst? It will allow to run multiple proxies on different localhost port.

By the way, how the proxy gets assigned? I noticed that it is always the same proxy URL which gets assigned for different lambda functions. I was expecting so see a different proxy for each lambda function. Is it a bug or it is intended.

I am using another tool for the deployment (claudiajs) because you don't support deploy on windows.

Thanks,

Clovis

**Comment by simocl** [comment]
I found this http://docs.bespoken.tools/en/latest/api/classes/lambdaserver.html
I will give a try...Please let me know if there is better way to handle this.

**Comment by jkelvie** [comment]
Hi, @simocl, it is correct that only one proxy can be run at a time on a machine. There are a couple factors that limit this - one is the unique ID that identifies your proxy instance. The other is the port that the LambdaServer (if you are testing with Lambdas runs on).

Can you tell me anything more about the use-case for where you would like to run multiple proxies? I might have an alternative suggestion.

**Comment by eemmzz** [comment]
Hi, we have a similar use case where we need to be able to proxy two different lambdas at once. Is this something you could add to Bespoken please?

**Comment by jkelvie** [comment]
Hi @eemmzz - one of the things we added was the ability to reference lambdas by name. The way it works is you start the proxy without specifying the lambda, like so:
```
bst proxy lambda
```

Then, when calling it, append the name and function of the lambda at the end, like this:
```
https://animated-vonnegut.bespoken.link/index.handler
```

If the lambda holding your code was index2, then you would append index2.handler. Does that help?

Here's a short animated gif demo of it in action:
![multiplelambdas](https://user-images.githubusercontent.com/17267/36772351-be7681a8-1c09-11e8-84aa-f490c963bde4.gif)
